name: "Deploy Actions"

on:
  push:
    branches: ["main"]

jobs:
  deploy-action:
    runs-on: ubuntu-latest
    steps:
      run: echo "Hacemos pull del código"
      run: echo "Correr migraciones"
      run: echo "Generar binario"
      run: echo "Publicar versión"